import type { Car } from "@/types";

export const PICKUP_LOCATIONS = [
  // Airports
  "Melbourne Airport (MEL)",
  "Avalon Airport (AVV)",

  // CBD & Inner City
  "CBD – Collins Street",
  "CBD – Flinders Street",
  "Docklands",
  "Southbank",
  "South Melbourne",

  // Inner Suburbs
  "South Yarra",
  "St Kilda",
  "Richmond",
  "Fitzroy",
  "Collingwood",
  "Carlton",
  "Brunswick",
  "Prahran",
  "Windsor",
  "Toorak",
  "Hawthorn",
  "Camberwell",

  // Eastern Suburbs
  "Box Hill",
  "Ringwood",
  "Croydon",
  "Lilydale",
  "Mooroolbark",
  "Doncaster",
  "Templestowe",
  "Nunawading",
  "Mitcham",
  "Vermont",

  // Northern Suburbs
  "Tullamarine",
  "Essendon",
  "Coburg",
  "Preston",
  "Reservoir",
  "Thomastown",
  "Epping",
  "Craigieburn",
  "Broadmeadows",
  "Bundoora",

  // Western Suburbs
  "Sunshine",
  "Footscray",
  "Werribee",
  "Hoppers Crossing",
  "Point Cook",
  "Altona",
  "Williamstown",
  "Melton",
  "Deer Park",
  "Laverton",

  // Southern Suburbs
  "Dandenong",
  "Frankston",
  "Moorabbin",
  "Cheltenham",
  "Springvale",
  "Noble Park",
  "Pakenham",
  "Cranbourne",
  "Berwick",
  "Narre Warren",

  // South-Eastern Suburbs
  "Glen Waverley",
  "Mount Waverley",
  "Mulgrave",
  "Wheelers Hill",
  "Clayton",
  "Oakleigh",
  "Chadstone",
  "Bentleigh",
  "Moorabbin Airport",
];

export const CARS: Car[] = [
  {
    id: "1",
    name: "Toyota Camry",
    brand: "Toyota",
    model: "Camry",
    year: 2024,
    category: "Compact",
    seats: 5,
    transmission: "Automatic",
    fuel: "Hybrid",
    pricePerDay: 89,
    imageUrl:
      "https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=800&q=80&auto=format&fit=crop",
    features: ["Bluetooth", "Backup Camera", "Apple CarPlay"],
    available: true,
    rating: 4.5,
    reviewCount: 128,
  },
  {
    id: "2",
    name: "Tesla Model 3",
    brand: "Tesla",
    model: "Model 3",
    year: 2024,
    category: "Luxury",
    seats: 5,
    transmission: "Automatic",
    fuel: "Electric",
    pricePerDay: 149,
    imageUrl:
      "https://images.unsplash.com/photo-1560958089-b8a1929cea89?w=800&q=80&auto=format&fit=crop",
    features: ["Autopilot", "15\" Touchscreen", "Free Charging"],
    available: true,
    rating: 4.9,
    reviewCount: 214,
  },
  {
    id: "3",
    name: "BMW X5",
    brand: "BMW",
    model: "X5 xDrive40i",
    year: 2024,
    category: "SUV",
    seats: 7,
    transmission: "Automatic",
    fuel: "Petrol",
    pricePerDay: 199,
    imageUrl:
      "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800&q=80&auto=format&fit=crop",
    features: ["Panoramic Sunroof", "Harman Kardon", "Heads-Up Display"],
    available: true,
    rating: 4.7,
    reviewCount: 89,
  },
  {
    id: "4",
    name: "Hyundai i30",
    brand: "Hyundai",
    model: "i30",
    year: 2023,
    category: "Economy",
    seats: 5,
    transmission: "Manual",
    fuel: "Petrol",
    pricePerDay: 59,
    imageUrl:
      "https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?w=800&q=80&auto=format&fit=crop",
    features: ["Lane Keep Assist", "Wireless Charging", "Rear Sensors"],
    available: true,
    rating: 4.3,
    reviewCount: 67,
  },
  {
    id: "5",
    name: "Mercedes GLE",
    brand: "Mercedes-Benz",
    model: "GLE 450",
    year: 2024,
    category: "Luxury",
    seats: 5,
    transmission: "Automatic",
    fuel: "Hybrid",
    pricePerDay: 259,
    imageUrl:
      "https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=800&q=80&auto=format&fit=crop",
    features: ["Burmester Sound", "MBUX AI", "Air Suspension"],
    available: false,
    rating: 4.8,
    reviewCount: 43,
  },
  {
    id: "6",
    name: "Ford Ranger",
    brand: "Ford",
    model: "Ranger XLT",
    year: 2023,
    category: "Van",
    seats: 5,
    transmission: "Automatic",
    fuel: "Diesel",
    pricePerDay: 129,
    imageUrl:
      "https://images.unsplash.com/photo-1590362891991-f776e747a588?w=800&q=80&auto=format&fit=crop",
    features: ["4WD", "Tow Package", "Sync 4 Infotainment"],
    available: true,
    rating: 4.6,
    reviewCount: 102,
  },
  {
    id: "7",
    name: "Kia EV6",
    brand: "Kia",
    model: "EV6 GT-Line",
    year: 2024,
    category: "Compact",
    seats: 5,
    transmission: "Automatic",
    fuel: "Electric",
    pricePerDay: 109,
    imageUrl:
      "https://images.unsplash.com/photo-1593941707882-a5bba14938c7?w=800&q=80&auto=format&fit=crop",
    features: ["800V Fast Charge", "Head-Up Display", "Meridian Sound"],
    available: true,
    rating: 4.7,
    reviewCount: 78,
  },
  {
    id: "8",
    name: "Toyota RAV4",
    brand: "Toyota",
    model: "RAV4 Hybrid",
    year: 2024,
    category: "SUV",
    seats: 5,
    transmission: "Automatic",
    fuel: "Hybrid",
    pricePerDay: 139,
    imageUrl:
      "https://images.unsplash.com/photo-1568844293986-8d0400bd4745?w=800&q=80&auto=format&fit=crop",
    features: ["AWD", "Safety Sense", "Apple CarPlay"],
    available: true,
    rating: 4.6,
    reviewCount: 155,
  },
];
